"""initial schema: all wfm modules

Revision ID: 2523b4fd7fa4
Revises: 
Create Date: 2026-07-03 22:20:07.457562
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2523b4fd7fa4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1024), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('attendance_codes',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('counts_as_shrinkage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attendance_codes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_codes')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_attendance_codes_organization_id'))
    )
    op.create_index(op.f('ix_attendance_codes_organization_id'), 'attendance_codes', ['organization_id'], unique=False)
    op.create_table('business_units',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_business_units_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_units')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_business_units_organization_id'))
    )
    op.create_index(op.f('ix_business_units_organization_id'), 'business_units', ['organization_id'], unique=False)
    op.create_table('holiday_calendars',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_holiday_calendars_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_calendars'))
    )
    op.create_index(op.f('ix_holiday_calendars_organization_id'), 'holiday_calendars', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('shift_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shift_type', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('breaks', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_shift_templates_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_templates'))
    )
    op.create_index(op.f('ix_shift_templates_organization_id'), 'shift_templates', ['organization_id'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_skills_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_skills_organization_id'))
    )
    op.create_index(op.f('ix_skills_organization_id'), 'skills', ['organization_id'], unique=False)
    op.create_table('countries',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('holiday_calendar_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['holiday_calendar_id'], ['holiday_calendars.id'], name=op.f('fk_countries_holiday_calendar_id_holiday_calendars'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_countries_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('organization_id', 'iso_code', name=op.f('uq_countries_organization_id'))
    )
    op.create_index(op.f('ix_countries_organization_id'), 'countries', ['organization_id'], unique=False)
    op.create_table('holidays',
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['holiday_calendars.id'], name=op.f('fk_holidays_calendar_id_holiday_calendars'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_index(op.f('ix_holidays_calendar_id'), 'holidays', ['calendar_id'], unique=False)
    op.create_table('lobs',
    sa.Column('business_unit_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('client', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_lobs_business_unit_id_business_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_lobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lobs')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_lobs_organization_id'))
    )
    op.create_index(op.f('ix_lobs_business_unit_id'), 'lobs', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_lobs_organization_id'), 'lobs', ['organization_id'], unique=False)
    op.create_table('queues',
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sla_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('sla_target_pct', sa.Float(), nullable=False),
    sa.Column('target_occupancy', sa.Float(), nullable=False),
    sa.Column('concurrency', sa.Float(), nullable=False),
    sa.Column('default_aht_seconds', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_queues_lob_id_lobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_queues_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues'))
    )
    op.create_index(op.f('ix_queues_lob_id'), 'queues', ['lob_id'], unique=False)
    op.create_index(op.f('ix_queues_organization_id'), 'queues', ['organization_id'], unique=False)
    op.create_table('teams',
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('leader_employee_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leader_employee_id'], ['employees.id'], name=op.f('fk_teams_leader_employee_id_employees'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_teams_lob_id_lobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_teams_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_lob_id'), 'teams', ['lob_id'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('capacity_plans',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=True),
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('starting_headcount', sa.Float(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_capacity_plans_lob_id_lobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_capacity_plans_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_capacity_plans_queue_id_queues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_plans'))
    )
    op.create_index(op.f('ix_capacity_plans_organization_id'), 'capacity_plans', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('shift_pattern', sa.String(length=32), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_employees_country_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_employees_lob_id_lobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employees_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_employees_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('organization_id', 'employee_code', name=op.f('uq_employees_organization_id'))
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_index(op.f('ix_employees_lob_id'), 'employees', ['lob_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_team_id'), 'employees', ['team_id'], unique=False)
    op.create_table('historical_series',
    sa.Column('queue_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('cleaning_report', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_historical_series_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_historical_series_queue_id_queues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historical_series'))
    )
    op.create_index(op.f('ix_historical_series_organization_id'), 'historical_series', ['organization_id'], unique=False)
    op.create_index(op.f('ix_historical_series_queue_id'), 'historical_series', ['queue_id'], unique=False)
    op.create_table('interval_actuals',
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offered', sa.Float(), nullable=False),
    sa.Column('handled', sa.Float(), nullable=False),
    sa.Column('aht_seconds', sa.Float(), nullable=False),
    sa.Column('service_level', sa.Float(), nullable=True),
    sa.Column('occupancy', sa.Float(), nullable=True),
    sa.Column('staffed', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_interval_actuals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_interval_actuals_queue_id_queues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interval_actuals')),
    sa.UniqueConstraint('queue_id', 'ts', name=op.f('uq_interval_actuals_queue_id'))
    )
    op.create_index(op.f('ix_interval_actuals_organization_id'), 'interval_actuals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_interval_actuals_queue_id'), 'interval_actuals', ['queue_id'], unique=False)
    op.create_index(op.f('ix_interval_actuals_ts'), 'interval_actuals', ['ts'], unique=False)
    op.create_table('schedules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_schedules_lob_id_lobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_schedules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_schedules_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_organization_id'), 'schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_schedules_team_id'), 'schedules', ['team_id'], unique=False)
    op.create_index(op.f('ix_schedules_week_start'), 'schedules', ['week_start'], unique=False)
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes_late', sa.Integer(), nullable=False),
    sa.Column('minutes_early_logout', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['attendance_codes.id'], name=op.f('fk_attendance_records_code_id_attendance_codes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attendance_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('employee_id', 'day', 'code_id', name=op.f('uq_attendance_records_employee_id'))
    )
    op.create_index(op.f('ix_attendance_records_day'), 'attendance_records', ['day'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_organization_id'), 'attendance_records', ['organization_id'], unique=False)
    op.create_table('capacity_plan_weeks',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('aht_override', sa.Float(), nullable=True),
    sa.Column('new_hires', sa.Float(), nullable=False),
    sa.Column('planned_attrition', sa.Float(), nullable=True),
    sa.Column('workload_hours', sa.Float(), nullable=False),
    sa.Column('required_fte', sa.Float(), nullable=False),
    sa.Column('available_hc', sa.Float(), nullable=False),
    sa.Column('gap', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['capacity_plans.id'], name=op.f('fk_capacity_plan_weeks_plan_id_capacity_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capacity_plan_weeks')),
    sa.UniqueConstraint('plan_id', 'week_start', name=op.f('uq_capacity_plan_weeks_plan_id'))
    )
    op.create_index(op.f('ix_capacity_plan_weeks_plan_id'), 'capacity_plan_weeks', ['plan_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_decided_by', sa.Uuid(), nullable=True),
    sa.Column('manager_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wfm_decided_by', sa.Uuid(), nullable=True),
    sa.Column('wfm_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_change_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_change_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_index(op.f('ix_change_requests_category'), 'change_requests', ['category'], unique=False)
    op.create_index(op.f('ix_change_requests_employee_id'), 'change_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_change_requests_organization_id'), 'change_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_skills_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_employee_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_skills')),
    sa.UniqueConstraint('employee_id', 'skill_id', name=op.f('uq_employee_skills_employee_id'))
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('queue_id', sa.Uuid(), nullable=True),
    sa.Column('series_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('backtest', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_forecasts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['forecasts.id'], name=op.f('fk_forecasts_parent_id_forecasts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_forecasts_queue_id_queues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['historical_series.id'], name=op.f('fk_forecasts_series_id_historical_series'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    op.create_index(op.f('ix_forecasts_organization_id'), 'forecasts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_forecasts_queue_id'), 'forecasts', ['queue_id'], unique=False)
    op.create_index(op.f('ix_forecasts_status'), 'forecasts', ['status'], unique=False)
    op.create_table('historical_points',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('aht', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['historical_series.id'], name=op.f('fk_historical_points_series_id_historical_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historical_points')),
    sa.UniqueConstraint('series_id', 'day', name=op.f('uq_historical_points_series_id'))
    )
    op.create_index(op.f('ix_historical_points_day'), 'historical_points', ['day'], unique=False)
    op.create_index(op.f('ix_historical_points_series_id'), 'historical_points', ['series_id'], unique=False)
    op.create_table('schedule_shifts',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_schedule_shifts_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_shifts_schedule_id_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['shift_templates.id'], name=op.f('fk_schedule_shifts_template_id_shift_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_shifts'))
    )
    op.create_index(op.f('ix_schedule_shifts_day'), 'schedule_shifts', ['day'], unique=False)
    op.create_index(op.f('ix_schedule_shifts_employee_id'), 'schedule_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_schedule_shifts_schedule_id'), 'schedule_shifts', ['schedule_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('forecast_points',
    sa.Column('forecast_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.Column('aht', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], name=op.f('fk_forecast_points_forecast_id_forecasts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_points')),
    sa.UniqueConstraint('forecast_id', 'day', name=op.f('uq_forecast_points_forecast_id'))
    )
    op.create_index(op.f('ix_forecast_points_day'), 'forecast_points', ['day'], unique=False)
    op.create_index(op.f('ix_forecast_points_forecast_id'), 'forecast_points', ['forecast_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('request_comments',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['change_requests.id'], name=op.f('fk_request_comments_request_id_change_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_comments'))
    )
    op.create_index(op.f('ix_request_comments_request_id'), 'request_comments', ['request_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_request_comments_request_id'), table_name='request_comments')
    op.drop_table('request_comments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_forecast_points_forecast_id'), table_name='forecast_points')
    op.drop_index(op.f('ix_forecast_points_day'), table_name='forecast_points')
    op.drop_table('forecast_points')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schedule_shifts_schedule_id'), table_name='schedule_shifts')
    op.drop_index(op.f('ix_schedule_shifts_employee_id'), table_name='schedule_shifts')
    op.drop_index(op.f('ix_schedule_shifts_day'), table_name='schedule_shifts')
    op.drop_table('schedule_shifts')
    op.drop_index(op.f('ix_historical_points_series_id'), table_name='historical_points')
    op.drop_index(op.f('ix_historical_points_day'), table_name='historical_points')
    op.drop_table('historical_points')
    op.drop_index(op.f('ix_forecasts_status'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_queue_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_organization_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_organization_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_employee_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_category'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_capacity_plan_weeks_plan_id'), table_name='capacity_plan_weeks')
    op.drop_table('capacity_plan_weeks')
    op.drop_index(op.f('ix_attendance_records_organization_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_day'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_schedules_week_start'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_team_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_organization_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_interval_actuals_ts'), table_name='interval_actuals')
    op.drop_index(op.f('ix_interval_actuals_queue_id'), table_name='interval_actuals')
    op.drop_index(op.f('ix_interval_actuals_organization_id'), table_name='interval_actuals')
    op.drop_table('interval_actuals')
    op.drop_index(op.f('ix_historical_series_queue_id'), table_name='historical_series')
    op.drop_index(op.f('ix_historical_series_organization_id'), table_name='historical_series')
    op.drop_table('historical_series')
    op.drop_index(op.f('ix_employees_team_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_lob_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_capacity_plans_organization_id'), table_name='capacity_plans')
    op.drop_table('capacity_plans')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_lob_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_queues_organization_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_lob_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_lobs_organization_id'), table_name='lobs')
    op.drop_index(op.f('ix_lobs_business_unit_id'), table_name='lobs')
    op.drop_table('lobs')
    op.drop_index(op.f('ix_holidays_calendar_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_countries_organization_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_skills_organization_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_shift_templates_organization_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_holiday_calendars_organization_id'), table_name='holiday_calendars')
    op.drop_table('holiday_calendars')
    op.drop_index(op.f('ix_business_units_organization_id'), table_name='business_units')
    op.drop_table('business_units')
    op.drop_index(op.f('ix_attendance_codes_organization_id'), table_name='attendance_codes')
    op.drop_table('attendance_codes')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
