"""add integrations and hc planning tables

Revision ID: 3b046bef4f12
Revises: 2523b4fd7fa4
Create Date: 2026-09-21 15:30:56.189045
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3b046bef4f12'
down_revision: str | None = '2523b4fd7fa4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.String(length=1200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('target_label', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_note', sa.String(length=600), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_actions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_actions'))
    )
    op.create_index(op.f('ix_agent_actions_agent'), 'agent_actions', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_actions_organization_id'), 'agent_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_run_id'), 'agent_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_status'), 'agent_actions', ['status'], unique=False)
    op.create_table('approval_requests',
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('approver_role', sa.String(length=48), nullable=False),
    sa.Column('assigned_om_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('queue_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('external_refs', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_via', sa.String(length=16), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=512), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_result', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_approval_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_assigned_om_id'), 'approval_requests', ['assigned_om_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_kind'), 'approval_requests', ['kind'], unique=False)
    op.create_index(op.f('ix_approval_requests_organization_id'), 'approval_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_source'), 'approval_requests', ['source'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('autonomy_policies',
    sa.Column('autonomy_level', sa.String(length=16), nullable=False),
    sa.Column('auto_apply_threshold', sa.Float(), nullable=False),
    sa.Column('agent_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_autonomy_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autonomy_policies')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_autonomy_policies_organization_id'))
    )
    op.create_index(op.f('ix_autonomy_policies_organization_id'), 'autonomy_policies', ['organization_id'], unique=False)
    op.create_table('integration_configs',
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('slack_webhook_url', sa.String(length=512), nullable=False),
    sa.Column('slack_bot_token', sa.String(length=512), nullable=False),
    sa.Column('slack_signing_secret', sa.String(length=512), nullable=False),
    sa.Column('slack_channel', sa.String(length=128), nullable=False),
    sa.Column('teams_enabled', sa.Boolean(), nullable=False),
    sa.Column('teams_webhook_url', sa.String(length=1024), nullable=False),
    sa.Column('teams_security_token', sa.String(length=512), nullable=False),
    sa.Column('default_approver_id', sa.Uuid(), nullable=True),
    sa.Column('auto_apply_on_approve', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integration_configs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_configs'))
    )
    op.create_index(op.f('ix_integration_configs_organization_id'), 'integration_configs', ['organization_id'], unique=False)
    op.create_table('approval_events',
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], name=op.f('fk_approval_events_approval_id_approval_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_events'))
    )
    op.create_index(op.f('ix_approval_events_approval_id'), 'approval_events', ['approval_id'], unique=False)
    op.create_table('hc_demand',
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('billable_fte', sa.Float(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_hc_demand_lob_id_lobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_hc_demand_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hc_demand')),
    sa.UniqueConstraint('organization_id', 'lob_id', 'month', name=op.f('uq_hc_demand_organization_id'))
    )
    op.create_index(op.f('ix_hc_demand_lob_id'), 'hc_demand', ['lob_id'], unique=False)
    op.create_index(op.f('ix_hc_demand_month'), 'hc_demand', ['month'], unique=False)
    op.create_index(op.f('ix_hc_demand_organization_id'), 'hc_demand', ['organization_id'], unique=False)
    op.create_table('hc_planning_configs',
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('ooo_shrinkage', sa.Float(), nullable=False),
    sa.Column('io_shrinkage', sa.Float(), nullable=False),
    sa.Column('attrition', sa.Float(), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('hiring_throughput', sa.Float(), nullable=False),
    sa.Column('training_throughput', sa.Float(), nullable=False),
    sa.Column('training_days', sa.Integer(), nullable=False),
    sa.Column('nesting_days', sa.Integer(), nullable=False),
    sa.Column('actuals_through', sa.String(length=7), nullable=True),
    sa.Column('tenure_bands', sa.JSON(), nullable=False),
    sa.Column('monthly_overrides', sa.JSON(), nullable=False),
    sa.Column('closing_overrides', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_hc_planning_configs_lob_id_lobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_hc_planning_configs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hc_planning_configs')),
    sa.UniqueConstraint('organization_id', 'lob_id', name=op.f('uq_hc_planning_configs_organization_id'))
    )
    op.create_index(op.f('ix_hc_planning_configs_lob_id'), 'hc_planning_configs', ['lob_id'], unique=False)
    op.create_index(op.f('ix_hc_planning_configs_organization_id'), 'hc_planning_configs', ['organization_id'], unique=False)
    op.create_table('new_hire_batches',
    sa.Column('lob_id', sa.Uuid(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('planned_hires', sa.Float(), nullable=False),
    sa.Column('experience_type', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('hiring_throughput', sa.Float(), nullable=True),
    sa.Column('training_throughput', sa.Float(), nullable=True),
    sa.Column('training_days', sa.Integer(), nullable=True),
    sa.Column('nesting_days', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], name=op.f('fk_new_hire_batches_lob_id_lobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_new_hire_batches_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_new_hire_batches'))
    )
    op.create_index(op.f('ix_new_hire_batches_hire_date'), 'new_hire_batches', ['hire_date'], unique=False)
    op.create_index(op.f('ix_new_hire_batches_lob_id'), 'new_hire_batches', ['lob_id'], unique=False)
    op.create_index(op.f('ix_new_hire_batches_organization_id'), 'new_hire_batches', ['organization_id'], unique=False)
    op.create_table('agent_planning_profiles',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('planning_status', sa.String(length=32), nullable=False),
    sa.Column('dop', sa.Date(), nullable=True),
    sa.Column('experience_type', sa.String(length=32), nullable=True),
    sa.Column('function', sa.String(length=64), nullable=True),
    sa.Column('current_function', sa.String(length=64), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('target_lob_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_agent_planning_profiles_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_planning_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_lob_id'], ['lobs.id'], name=op.f('fk_agent_planning_profiles_target_lob_id_lobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_planning_profiles')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_agent_planning_profiles_employee_id'))
    )
    op.create_index(op.f('ix_agent_planning_profiles_employee_id'), 'agent_planning_profiles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_agent_planning_profiles_organization_id'), 'agent_planning_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_planning_profiles_organization_id'), table_name='agent_planning_profiles')
    op.drop_index(op.f('ix_agent_planning_profiles_employee_id'), table_name='agent_planning_profiles')
    op.drop_table('agent_planning_profiles')
    op.drop_index(op.f('ix_new_hire_batches_organization_id'), table_name='new_hire_batches')
    op.drop_index(op.f('ix_new_hire_batches_lob_id'), table_name='new_hire_batches')
    op.drop_index(op.f('ix_new_hire_batches_hire_date'), table_name='new_hire_batches')
    op.drop_table('new_hire_batches')
    op.drop_index(op.f('ix_hc_planning_configs_organization_id'), table_name='hc_planning_configs')
    op.drop_index(op.f('ix_hc_planning_configs_lob_id'), table_name='hc_planning_configs')
    op.drop_table('hc_planning_configs')
    op.drop_index(op.f('ix_hc_demand_organization_id'), table_name='hc_demand')
    op.drop_index(op.f('ix_hc_demand_month'), table_name='hc_demand')
    op.drop_index(op.f('ix_hc_demand_lob_id'), table_name='hc_demand')
    op.drop_table('hc_demand')
    op.drop_index(op.f('ix_approval_events_approval_id'), table_name='approval_events')
    op.drop_table('approval_events')
    op.drop_index(op.f('ix_integration_configs_organization_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_autonomy_policies_organization_id'), table_name='autonomy_policies')
    op.drop_table('autonomy_policies')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_source'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_organization_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_kind'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_assigned_om_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_actions_status'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_run_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_organization_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_agent'), table_name='agent_actions')
    op.drop_table('agent_actions')
    # ### end Alembic commands ###
